/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package editor;

import java.awt.Color;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author student
 */
public class FontDialog extends javax.swing.JDialog {

    private Font pismo;
    private Color barva;
    private String actionButton = "Storno";

    /**
     * Creates new form FontDialog
     */
    public FontDialog(java.awt.Frame parent, boolean modal, Font font, Color color) {
        super(parent, modal);
        this.pismo = font;
        this.barva = color;
        initComponents();

        try {
            String[] fontList = GraphicsEnvironment.getLocalGraphicsEnvironment().getAvailableFontFamilyNames();
            for (String s : fontList) {
                typPisma.addItem(s);
            }
            String fontFamily = font.getFamily();
            for (int i = 0; i < typPisma.getItemCount(); i++) {
                if (fontFamily.equalsIgnoreCase(typPisma.getItemAt(i).toString())) {
                    typPisma.setSelectedIndex(i);
                    break;
                }
            }
        } catch (Exception e) {
               JOptionPane.showMessageDialog(this.getParent(), "Nastala chyba při načítání fontů", "Chyba!", JOptionPane.ERROR_MESSAGE);
        }
        this.setUkazka();
    }
        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
     * @return 
         */
    public String showDialog(){
    this.setVisible(true);
    return actionButton;
    }
    
    public Font getPismo() {
    return pismo;
    }
    
    public Color getBarva() {
    return barva;
    }
    
    private void setUkazka() {
    velikostPisma.setValue(pismo.getSize());
    barvaPisma.setOpaque(true);
    barvaPisma.setForeground(barva);
    barvaPisma.setBackground(barva);
    
    if((pismo.getStyle( )& Font.BOLD) == Font.BOLD) {
        tucne.setSelected(true);
    }else if ((pismo.getStyle() & Font.ITALIC) == Font.ITALIC) {
        kurziva.setSelected(true);
    }else {
        obycejne.setSelected(true);
    }
    ukazka.setFont(pismo);
    ukazka.setForeground(barva);
    }
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        OKButton = new javax.swing.JButton();
        StornoButton = new javax.swing.JButton();
        obycejne = new javax.swing.JRadioButton();
        kurziva = new javax.swing.JRadioButton();
        tucne = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        velikostPisma = new javax.swing.JSpinner();
        typPisma = new javax.swing.JComboBox();
        ukazka = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nastavení Písma");
        setLocationByPlatform(true);
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setName("fontDialog"); // NOI18N
        setResizable(false);

        jLabel1.setText("Typ písma");

        jLabel2.setText("Velikost písma");

        jLabel3.setText("Řez písma");

        jLabel4.setText("Barva písma");

        OKButton.setText("OK");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        StornoButton.setText("Storno");

        obycejne.setText("obyčejné");
        obycejne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obycejneActionPerformed(evt);
            }
        });

        kurziva.setText("kurzíva");

        tucne.setText("tučné");
        tucne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tucneActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel5.setOpaque(true);

        typPisma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typPismaActionPerformed(evt);
            }
        });

        ukazka.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ukazka.setText("Ukázka");
        ukazka.setToolTipText("");
        ukazka.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ukazka, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(109, 109, 109)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kurziva)
                                    .addComponent(obycejne)
                                    .addComponent(tucne)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(OKButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(StornoButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(99, 99, 99)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(91, 91, 91)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(velikostPisma, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(typPisma, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(27, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(typPisma, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(velikostPisma, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(obycejne))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kurziva, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(tucne)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ukazka, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OKButton)
                    .addComponent(StornoButton))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>                        

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
    
        actionButton = "OK";
        this.setVisible(false);
        this.dispose();
    }                                        
    
    private void stornoButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
        actionButton = "storno";
        this.setVisible(false);
        this.dispose();
    } 
    
    private void velikostPismaStateChanged(java.awt.event.ActionEvent evt) {                                         
       pismo = new Font(pismo.getFamily(), pismo.getStyle(),(int) velikostPisma.getValue());
        this.setUkazka();
    } 
    
    private void obycejneActionPerformed(java.awt.event.ActionEvent evt) {                                         
        pismo = pismo.deriveFont(Font.ITALIC);
    this.setUkazka();
    }                                        

    private void tucneActionPerformed(java.awt.event.ActionEvent evt) {                                      
       pismo = pismo.deriveFont(Font.BOLD);
    this.setUkazka();
    }                                     

    private void typPismaActionPerformed(java.awt.event.ActionEvent evt) {                                         
       pismo = new Font((String) typPisma.getSelectedItem(), pismo.getStyle(), pismo.getSize());
       this.setUkazka();
    }                                        
    
    private void kurzivaActionPerformed(java.awt.event.ActionEvent evt) {
    pismo = pismo.deriveFont(Font.ITALIC);
    this.setUkazka();
    }
    
    private void barvaPismaMouseClicked(java.awt.event.ActionEvent evt) {
    barva = JColorChooser.showDialog(this, "Vyber barvu textu", barva);
    this.setUkazka();
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton OKButton;
    private javax.swing.JButton StornoButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton kurziva;
    private javax.swing.JRadioButton obycejne;
    private javax.swing.JRadioButton tucne;
    private javax.swing.JComboBox typPisma;
    private javax.swing.JLabel ukazka;
    private javax.swing.JSpinner velikostPisma;
    // End of variables declaration                   


    private static class barvaPisma {

        private static void setBackground(Color barva) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        private static void setOpaque(boolean b) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        private static void setForeground(Color barva) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public barvaPisma() {
        }
    }
}
